name: medcon_storage
description: "A new Flutter project."
publish_to: 'none' # Remove this if you plan to publish to pub.dev
version: 2.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.0.0
  file_selector: ^1.0.2
  path_provider: ^2.1.3
  flutter_launcher_icons: ^0.14.3
  flutter_secure_storage: ^9.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/smalllogo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/smalllogo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/smalllogo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "/Users/majdahmad/Documents/projects/medcon-storage/assets/smalllogo.png"
